### PR TITLE
add imaging movie script

### PR DESCRIPTION
**Pull request by sageyu123**

### CODE REVIEW

**Comment by binchensun** [comment]
I do not see mstools.getphasecenter in suncasa.utils. Did you just add it? Pull request to that too? Also my lines only work for EOVSA, as the phasecenter in FIELD is always solar center.

**Comment by binchensun** [comment]
I found a "mstools" in the suncasa version on Virgo, but it does not have your function.
CASA <3>: mstools??
Type:        module
String form: <module 'suncasa.utils.mstools' from '/common/software/SunCASA/SunCASA-0.7.5_Pre-release.el7/solar-packages/suncasa/utils/mstools.py'>
File:        /common/software/SunCASA/SunCASA-0.7.5_Pre-release.el7/solar-packages/suncasa/utils/mstools.py
Source:     
from taskinit import tb

def msclearhistory(msfile):
    '''Clears history in the a measurement sets file

    :param msfile: string
            The name of a measurement sets file

    :return:
    '''

    tb.open(msfile + '/HISTORY', nomodify=False)
    nrows = tb.nrows()
    if nrows > 0:
        tb.removerows(range(nrows))
    tb.close()

**Comment by sageyu123** [comment]
SOrry, I thought I created a pull request but I didn’t. And the SunCASA on Virgo are updated now. 

-Sijie

**Comment by sageyu123** [comment]
I added the observatory check in mstools. It should be fine.
-Sijie

**Pull request closed without merging**
